# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

abs2 <- function(x) {
    .Call(`_hlt_abs2`, x)
}

lgp1PNR <- function(x, lambda, nT, n, J, tJ, nDmax, lJ, theta, d, eps) {
    .Call(`_hlt_lgp1PNR`, x, lambda, nT, n, J, tJ, nDmax, lJ, theta, d, eps)
}

lt1PNR <- function(x, iter, burn, delta, post, mean_theta, mean_theta_sq, draw, draw_theta, ix, ixe, npar, ntheta, n, J, nDmax, lJ, nT, tJ, accept, eps, display_progress = TRUE) {
    .Call(`_hlt_lt1PNR`, x, iter, burn, delta, post, mean_theta, mean_theta_sq, draw, draw_theta, ix, ixe, npar, ntheta, n, J, nDmax, lJ, nT, tJ, accept, eps, display_progress)
}

lgp1PNR2D <- function(x, lambda, nT, n, J, tJ, nDmax, lJ, theta, d, eps) {
    .Call(`_hlt_lgp1PNR2D`, x, lambda, nT, n, J, tJ, nDmax, lJ, theta, d, eps)
}

lt1PNR2D <- function(x, iter, burn, delta, post, mean_theta, mean_theta_sq, draw, draw_theta, ix, ixe, npar, ntheta, n, J, nDmax, lJ, nT, tJ, accept, eps, display_progress = TRUE) {
    .Call(`_hlt_lt1PNR2D`, x, iter, burn, delta, post, mean_theta, mean_theta_sq, draw, draw_theta, ix, ixe, npar, ntheta, n, J, nDmax, lJ, nT, tJ, accept, eps, display_progress)
}

lgp1PR <- function(x, z, lambda, nB, nT, n, J, tJ, nDmax, lJ, theta, d, beta, eps) {
    .Call(`_hlt_lgp1PR`, x, z, lambda, nB, nT, n, J, tJ, nDmax, lJ, theta, d, beta, eps)
}

lt1PR <- function(x, z, iter, burn, delta, post, mean_theta, mean_theta_sq, draw, draw_theta, ix, ixe, npar, ntheta, n, nB, J, nDmax, lJ, nT, tJ, accept, eps, display_progress = TRUE) {
    .Call(`_hlt_lt1PR`, x, z, iter, burn, delta, post, mean_theta, mean_theta_sq, draw, draw_theta, ix, ixe, npar, ntheta, n, nB, J, nDmax, lJ, nT, tJ, accept, eps, display_progress)
}

lgp1PR2D <- function(x, z, lambda, nB, nT, n, J, tJ, nDmax, lJ, theta, d, beta, eps) {
    .Call(`_hlt_lgp1PR2D`, x, z, lambda, nB, nT, n, J, tJ, nDmax, lJ, theta, d, beta, eps)
}

lt1PR2D <- function(x, z, iter, burn, delta, post, mean_theta, mean_theta_sq, draw, draw_theta, ix, ixe, npar, ntheta, n, nB, J, nDmax, lJ, nT, tJ, accept, eps, display_progress = TRUE) {
    .Call(`_hlt_lt1PR2D`, x, z, iter, burn, delta, post, mean_theta, mean_theta_sq, draw, draw_theta, ix, ixe, npar, ntheta, n, nB, J, nDmax, lJ, nT, tJ, accept, eps, display_progress)
}

lgp2PNR <- function(x, lambda, nT, n, J, tJ, nDmax, lJ, theta, d, a, eps) {
    .Call(`_hlt_lgp2PNR`, x, lambda, nT, n, J, tJ, nDmax, lJ, theta, d, a, eps)
}

lt2PNR <- function(x, iter, burn, delta, post, mean_theta, mean_theta_sq, draw, draw_theta, ix, ixe, npar, ntheta, n, J, nDmax, lJ, nT, tJ, accept, eps, display_progress = TRUE) {
    .Call(`_hlt_lt2PNR`, x, iter, burn, delta, post, mean_theta, mean_theta_sq, draw, draw_theta, ix, ixe, npar, ntheta, n, J, nDmax, lJ, nT, tJ, accept, eps, display_progress)
}

lgp2PNR2D <- function(x, lambda, nT, n, J, tJ, nDmax, lJ, theta, d, a, eps) {
    .Call(`_hlt_lgp2PNR2D`, x, lambda, nT, n, J, tJ, nDmax, lJ, theta, d, a, eps)
}

lt2PNR2D <- function(x, iter, burn, delta, post, mean_theta, mean_theta_sq, draw, draw_theta, ix, ixe, npar, ntheta, n, J, nDmax, lJ, nT, tJ, accept, eps, display_progress = TRUE) {
    .Call(`_hlt_lt2PNR2D`, x, iter, burn, delta, post, mean_theta, mean_theta_sq, draw, draw_theta, ix, ixe, npar, ntheta, n, J, nDmax, lJ, nT, tJ, accept, eps, display_progress)
}

lgp2PR <- function(x, z, lambda, nB, nT, n, J, tJ, nDmax, lJ, theta, d, a, beta, eps) {
    .Call(`_hlt_lgp2PR`, x, z, lambda, nB, nT, n, J, tJ, nDmax, lJ, theta, d, a, beta, eps)
}

lt2PR <- function(x, z, iter, burn, delta, post, mean_theta, mean_theta_sq, draw, draw_theta, ix, ixe, npar, ntheta, n, nB, J, nDmax, lJ, nT, tJ, accept, eps, display_progress = TRUE) {
    .Call(`_hlt_lt2PR`, x, z, iter, burn, delta, post, mean_theta, mean_theta_sq, draw, draw_theta, ix, ixe, npar, ntheta, n, nB, J, nDmax, lJ, nT, tJ, accept, eps, display_progress)
}

lgp2PR2D <- function(x, z, lambda, nB, nT, n, J, tJ, nDmax, lJ, theta, d, a, beta, eps) {
    .Call(`_hlt_lgp2PR2D`, x, z, lambda, nB, nT, n, J, tJ, nDmax, lJ, theta, d, a, beta, eps)
}

lt2PR2D <- function(x, z, iter, burn, delta, post, mean_theta, mean_theta_sq, draw, draw_theta, ix, ixe, npar, ntheta, n, nB, J, nDmax, lJ, nT, tJ, accept, eps, display_progress = TRUE) {
    .Call(`_hlt_lt2PR2D`, x, z, iter, burn, delta, post, mean_theta, mean_theta_sq, draw, draw_theta, ix, ixe, npar, ntheta, n, nB, J, nDmax, lJ, nT, tJ, accept, eps, display_progress)
}

