# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

amc <- function(x, x_start, iter, burn, greedy_iterations, a, data, lp_select, accept, validation_indexes, validation_lower, p_reg) {
    .Call(`_lmHOIRT_amc`, x, x_start, iter, burn, greedy_iterations, a, data, lp_select, accept, validation_indexes, validation_lower, p_reg)
}

lognorm_dens_dx <- function(x, mean, sd) {
    .Call(`_lmHOIRT_lognorm_dens_dx`, x, mean, sd)
}

logtruncnorm_dens_dx <- function(x, mean, sd, a, b) {
    .Call(`_lmHOIRT_logtruncnorm_dens_dx`, x, mean, sd, a, b)
}

log_normd_dx <- function(x, mean, sd) {
    .Call(`_lmHOIRT_log_normd_dx`, x, mean, sd)
}

log_unifd_dx <- function(x, l, u) {
    .Call(`_lmHOIRT_log_unifd_dx`, x, l, u)
}

min <- function(a, b) {
    .Call(`_lmHOIRT_min`, a, b)
}

lp_2pl_logit <- function(x, data) {
    .Call(`_lmHOIRT_lp_2pl_logit`, x, data)
}

lp_2pl_logit_reg <- function(x, data, p) {
    .Call(`_lmHOIRT_lp_2pl_logit_reg`, x, data, p)
}

validate_proposal <- function(proposal, indexes, lower) {
    .Call(`_lmHOIRT_validate_proposal`, proposal, indexes, lower)
}

